services:
  - type: web
    name: emp-portal
    env: node
    buildCommand: >
      npm install &&
      cd client && npm install && npm run build && cd .. &&
      npx prisma migrate deploy
    startCommand: node server/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: emp-db
          property: connectionString

databases:
  - name: emp-db
    plan: free
